[workspace]
members = ["proto", "p2p", "miner", "wallet"]

[package]
name = "coin"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
hex = "0.4"
coin-proto = { path = "proto" }
bs58 = "0.5"
prost = "0.12"

[dev-dependencies]
tempfile = "3"
