# Example configuration for coin-p2p
listeners:
  - ip: "0.0.0.0"
    port: 9000
# Optional wallet address to receive mining rewards
wallet_address: "1BvgsfsZQVtkLS69NvGF8rw6NZW2ShJQHr"
# Node type: Wallet, Miner or Verifier
node_type: Miner
# Where the blockchain is stored on disk
chain_file: "chain.bin"
# List of peers to connect to on startup
seed_peers:
  - "127.0.0.1:9001"
max_msgs_per_sec: 10
max_peers: 32
mining_threads: 1
# Optional SOCKS5 proxy (Tor). Example: "127.0.0.1:9050"
tor_proxy: null
