# Example configuration for coin-p2p
listeners:
  - ip: "0.0.0.0"
    port: 9000
# Optional wallet address to receive mining rewards
wallet_address: "1BvgsfsZQVtkLS69NvGF8rw6NZW2ShJQHr"
# Node type: Wallet, Miner or Verifier
node_type: Miner
# Directory where block files are stored
block_dir: "blocks"
# List of peers to connect to on startup
seed_peers:
  - "127.0.0.1:9001"
max_msgs_per_sec: 10
# mining_threads is optional. When omitted, all CPU cores are used.
max_peers: 32
# mining_threads: 4
# Prune transactions from blocks older than this many confirmations
prune_depth: 100
# Optional SOCKS5 proxy (Tor). Example: "127.0.0.1:9050"
tor_proxy: null
