listeners:
  - ip: "0.0.0.0"
    port: 9000
wallet_address: "1BvgsfsZQVtkLS69NvGF8rw6NZW2ShJQHr"
node_type: Miner
block_dir: "blocks"
seed_peers:
  - "127.0.0.1:9001"
max_msgs_per_sec: 10
max_peers: 32
# mining_threads controls the number of CPU threads used for mining.
# When omitted the software automatically uses all available cores.
# mining_threads: 4
prune_depth: 100
tor_proxy: null
