[package]
name = "coin-wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
hex = "0.4"
bs58 = "0.5"
sha2 = "0.10"
ripemd = "0.1"
secp256k1 = "0.27"
pbkdf2 = "0.12"
hmac = "0.12"

[dev-dependencies]
hex-literal = "0.4"
