[package]
name = "stake"
version = "0.1.0"
edition = "2024"

[dependencies]
coin = { path = ".." }
secp256k1 = { version = "0.27", features = ["recovery"] }
sha2 = "0.10"
ripemd = "0.1"
bs58 = "0.5"
bincode = "1"
