[package]
name = "contract-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmi = "0.31"
serde = { version = "1", features = ["derive"] }
coin-proto = { path = "../proto" }
anyhow = "1"
serde_json = "1"

[dev-dependencies]
wat = "1"
tempfile = "3"
serial_test = "2"
