[package]
name = "coin-proto"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
prost = "0.12"
prost-derive = "0.12"

[build-dependencies]
prost-build = "0.12"
protoc-bin-vendored = "3"

